[profile.default]
evm_version = 'shanghai'
src = "src"
out = "out"
libs = [
    'node_modules/@layerzerolabs/toolbox-foundry/lib',
    'node_modules',
]
solc = "0.8.23"

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    "@tokenized-strategy/=lib/tokenized-strategy/src/",
    "@periphery/=lib/tokenized-strategy-periphery/src/",
    "@uniswap-periphery/=lib/v3-periphery/contracts/",
    "@uniswap-core/=lib/v3-core/contracts/",
    '@layerzerolabs/=node_modules/@layerzerolabs/',
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
ble = "${BLE_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
unknown_chain = { key = "${TENDERLY_ACCESS_KEY}", chain = 73571, url = "${TENDERLY_VIRTUAL_TESTNET_RPC_URL}/verify/etherscan" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
